/*
  action types for reducer to call 
 */

// ProductDetail Actions
export enum ShopActionType {
  SET_SHOP_PRODUCTS = "SET_SHOP_PRODUCTS",
  FETCH_SHOP_PRODUCTS = "FETCH_SHOP_PRODUCTS",
  FETCH_ALL_BEST_SELLER_PRODUCTS = "FETCH_ALL_BEST_SELLER_PRODUCTS",
  SET_ALL_BEST_SELLER_PRODUCTS = "SET_ALL_BEST_SELLER_PRODUCTS",
}
