/*
  action types for reducer to call 
 */

// ProductDetail Actions
export enum ShopActionType {
  SET_SHOP_PRODUCTS = "SET_SHOP_PRODUCTS",
  FETCH_SHOP_PRODUCTS = "FETCH_SHOP_PRODUCTS",
  FETCH_ALL_BEST_SELLER_PRODUCTS = "FETCH_ALL_BEST_SELLER_PRODUCTS",
  SET_ALL_BEST_SELLER_PRODUCTS = "SET_ALL_BEST_SELLER_PRODUCTS",
  FETCH_SHOP_PRODUCTS_AND_FILTERS = "FETCH_SHOP_PRODUCTS_AND_FILTERS",
  SET_SHOP_PRODUCTS_AND_FILTERS = "SET_SHOP_PRODUCTS_AND_FILTERS",
}

export enum UserActionType {
  UPDATE_USER_SHOP_PRODUCTS_PAGE = "UPDATE_USER_SHOP_PRODUCTS_PAGE",
  UPDATE_USER_FILTERS = "UPDATE_USER_FILTERS",
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CLEAN_CART = "CLEAN_CART",
}
